# Generated by Django 2.1.7 on 2019-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190303_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='ccdfile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='fhirfile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='ocrfile',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
