# Generated by Django 2.1.7 on 2019-03-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190303_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='ccdfile',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='fhirfile',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='ocrfile',
        ),
    ]
