# Generated by Django 2.1.7 on 2019-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_aadharmodel_generalpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpatient',
            name='image_patient',
        ),
        migrations.RemoveField(
            model_name='generalpatient',
            name='uni_adhaar_id',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='imageids',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='aadharModel',
        ),
        migrations.DeleteModel(
            name='generalPatient',
        ),
    ]
